import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../models/extracted_report_data.dart';

class PdfGenerator {
  static Future<File> generateReportPdf(ExtractedReportData data) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            _buildHeader(data),
            pw.SizedBox(height: 20),
            _buildPatientInfo(data),
            pw.SizedBox(height: 20),
            if (data.testResults != null && data.testResults!.isNotEmpty)
              _buildTestResults(data.testResults!),
            if (data.diagnosis != null) ...[
              pw.SizedBox(height: 20),
              _buildSection('Diagnosis', data.diagnosis!),
            ],
            if (data.observations != null) ...[
              pw.SizedBox(height: 20),
              _buildSection('Observations', data.observations!),
            ],
            pw.SizedBox(height: 20),
            _buildFooter(data),
          ];
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File(
      '${output.path}/report_${data.reportDate.replaceAll('/', '-')}.pdf',
    );
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildHeader(ExtractedReportData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Medical Report',
          style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Text('Type: ${data.reportType}'),
        pw.Text('Date: ${data.reportDate}'),
      ],
    );
  }

  static pw.Widget _buildPatientInfo(ExtractedReportData data) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Patient Information',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
          pw.Divider(),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Name: ${data.patientInfo.name}'),
              pw.Text('Age: ${data.patientInfo.age}'),
              pw.Text('Gender: ${data.patientInfo.gender}'),
            ],
          ),
          if (data.doctorInfo != null) ...[
            pw.SizedBox(height: 10),
            pw.Text('Doctor: ${data.doctorInfo!.name}'),
            if (data.doctorInfo!.hospital != null)
              pw.Text('Hospital: ${data.doctorInfo!.hospital}'),
          ],
        ],
      ),
    );
  }

  static pw.Widget _buildTestResults(List<TestResult> results) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Test Results',
          style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 10),
        pw.Table.fromTextArray(
          headers: ['Test Name', 'Value', 'Unit', 'Ref. Range', 'Status'],
          data: results
              .map((r) => [r.name, r.value, r.unit, r.normalRange, r.status])
              .toList(),
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
          cellHeight: 30,
          cellAlignments: {
            0: pw.Alignment.centerLeft,
            1: pw.Alignment.center,
            2: pw.Alignment.center,
            3: pw.Alignment.center,
            4: pw.Alignment.center,
          },
        ),
      ],
    );
  }

  static pw.Widget _buildSection(String title, String content) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 5),
        pw.Text(content),
      ],
    );
  }

  static pw.Widget _buildFooter(ExtractedReportData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Divider(),
        pw.Text(
          'Generated by MediScan',
          style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10),
        ),
      ],
    );
  }
}
